# Default values for compss-matmul.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: oriolmac/compss-matmul-prom
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: 3.3

compss:
  # namespace: {}
  master:
    labels:
      node: master
    ports:
      name: ssh
    # local volume in node where the master is executed
    volume: {}
    #  localPath: /tmp/compss-matmul-results   # it has to exist locally
    #  node: agx12

  worker:
    number: 2
    labels:
      node: worker
    resources:
      cpu: 4
      memory: 4  # in gigabytes
    ports:
      name: ssh

  service:
    ssh: 22

matmulparams:
  b: 6
  e: 246
  iterations: 25   # number of times the application will do the matrix multiplication
  context: 
    folderPath: /home/omartinez/compss-matmul/matmul
    file: matmul.py

prometheusclient:
  buckets: "-inf, 0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.01, 0.1, 1, 10, 50, 100, 200, inf" # Histogram bucket