apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-worker
  labels:
    {{- include "compss-matmul.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      pod-hostname: worker
  serviceName: {{ .Release.Name }}
  replicas: {{ $.Values.compss.worker.number }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        pod-hostname: worker
    spec:
      terminationGracePeriodSeconds: 5
      subdomain: {{ .Release.Name }}
      dnsConfig:
        searches:
        - {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "/usr/sbin/sshd", "-D" ]
        resources:
          limits:
            memory: {{ $.Values.compss.worker.resources.memory }}G
            cpu: {{ $.Values.compss.worker.resources.cpu }}
        ports:
        - containerPort: 22
          name: {{ $.Values.compss.worker.ports.name }}
